Fix working directories for Podman versions <1.4.3

diff --git a/t3 b/t3
--- a/t3
+++ b/t3
@@ -148,6 +148,36 @@ err_exit() {
 
 # --------------------------------------------------------------------------
 
+# Compares two version numbers formatted as x[.y[.z]] and echoes a number
+# <0, ==0 or >0 to stdout if the first one is less than, equal to or greater
+# than the second one, respectively.
+#
+# Returns a non-zero status and does not echo anything if either number is
+# ill-formatted.
+#
+# Arguments:
+#   $1  first version number
+#   $2  second version number
+compare_versions() {
+    local V1="$1".0.0
+    local V2="$2".0.0
+    local RE='([0-9]+)\.([0-9]+)\.([0-9]+)'
+
+    [[ "$V1" =~ $RE ]] || return 1
+    local MAJOR1=${BASH_REMATCH[1]}
+    local MINOR1=${BASH_REMATCH[2]}
+    local REV1=${BASH_REMATCH[3]}
+
+    [[ "$V2" =~ $RE ]] || return 1
+    local DIFF=$(( $MAJOR1 - ${BASH_REMATCH[1]} ))
+    [ $DIFF -ne 0 ] || DIFF=$(( $MINOR1 - ${BASH_REMATCH[2]} ))
+    [ $DIFF -ne 0 ] || DIFF=$(( $REV1 - ${BASH_REMATCH[3]} ))
+    echo $DIFF
+}
+
+
+# --------------------------------------------------------------------------
+
 # Returns success if the argument contains a '/'.
 #
 # Arguments:
@@ -1060,18 +1090,7 @@ case $ENGINE_NAME in
         ENV_OPTIONS="$ENV_OPTIONS \
             --env $HOST_IP_ENV"
         # Note: as of Podman 1.6.0, the property name changed from 'MountPoint' to 'Mountpoint' (as in Docker)
-        case "$ENGINE_VERSION" in
-            *' '0.*)
-                ;&
-
-            *' '1.[012345].*)
-                MP_FORMAT='{{.MountPoint}}'
-                ;;
-
-            *)
-                MP_FORMAT='{{.Mountpoint}}'
-                ;;
-        esac
+        [ $(compare_versions "$ENGINE_VERSION" '1.6.0') -ge 0 ] && MP_FORMAT='{{.Mountpoint}}' || MP_FORMAT='{{.MountPoint}}'
         SUDO_PREFIX=
         ;;
 esac
@@ -1219,8 +1238,9 @@ case "$CMD" in
 
         # Collect volume names from container
         # Note: prior to Podman v1.4.3, the volume name was contained in property .Source, not .Name
+        [ $(compare_versions "$ENGINE_VERSION" '1.4.3') -ge 0 ] && NAME_PROP='.Name' || NAME_PROP='.Source'
         VOLNAMES=$($T3_ENGINE container inspect \
-            --format='{{range .Mounts}}{{if eq .Destination "'$T3_ROOTDIR'" "'$T3_DATADIR'"}}{{printf "%s " .Name}}{{end}}{{end}}' \
+            --format='{{range .Mounts}}{{if eq .Destination "'$T3_ROOTDIR'" "'$T3_DATADIR'"}}{{printf "%s " '$NAME_PROP'}}{{end}}{{end}}' \
             "$T3_NAME" 2>/dev/null)
 
         # Try to unmount whatever may be mounted at the mountpoint of each volume
