Add --certfiles option

diff --git a/t3 b/t3
--- a/t3
+++ b/t3
@@ -26,6 +26,7 @@
 T3_IMAGE=undecaf/typo3-in-a-box
 T3_ROOTDIR=/var/www/localhost
 T3_DATADIR=/var/lib/typo3-db
+CERT_BASENAME=$T3_ROOTDIR/.ssl/custom
 FILE_LIMIT='nofile=10000:15000'
 
 # --------------------------------------------------------------------------
@@ -307,8 +308,11 @@ Options (default values can be overridden by environment variables):
       port will not be published.
       Default: \$T3_PORTS, or '127.0.0.1:8080,127.0.0.1:8443'.
 
-  --keyfiles=PRIVATE-KEY,CERT, -k PRIVATE-KEY,CERT
-      TODO
+  --certfiles=PRIVATE-KEY,CERT, -k PRIVATE-KEY,CERT
+      Private key file and certificate file (PEM format) for HTTPS connections,
+      located at the host. If not specified then a self-signed certificate will
+      be used for HTTPS connections.
+      Default: \$T3_CERTFILES, or empty.
 
   --db-type=TYPE, -d TYPE
       Type of database to use: 'sqlite' or empty for SQLite, 'mariadb' for 
@@ -345,7 +349,7 @@ described above. If necessary, '--' can be used to separate them from the $(base
  
 EOT
         )
-        ALLOWED_OPTS='-d|--db-type(=.*)?|-e|--engine(=.+)?|-h|--hostname(=.+)?|-n|--name(=.+)?|-t|--tag(=.+)?|-c|--composer-mode|-v|--typo3-root(=.+)?|-V|--db-data(=.+)?|-p|--typo3-ports(=.+)?|-P|--db-port(=.+)?|-s|--show'
+        ALLOWED_OPTS='-d|--db-type(=.*)?|-e|--engine(=.+)?|-h|--hostname(=.+)?|-n|--name(=.+)?|-t|--tag(=.+)?|-c|--composer-mode|-v|--typo3-root(=.+)?|-V|--db-data(=.+)?|-p|--typo3-ports(=.+)?|-k|--certfiles(=.+)?|-P|--db-port(=.+)?|-s|--show'
         ;;
 
 
@@ -713,6 +717,16 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
 
+        # Private key file and certificate file
+        -k|--certfiles)
+            shift
+            ;&
+
+        --certfiles=*)
+            T3_CERTFILES="${1#--certfiles=}"
+            shift
+            ;;
+
         # Database port
         -P|--db-port)
             shift
@@ -781,13 +795,21 @@ case $ENGINE_NAME in
         ;;
 esac
 
-# TYPO3 ports and interfaces
-HTTP_PORT=${T3_PORTS%%,*}
-HTTPS_PORT=${T3_PORTS##*,}
+# Split into HTTP and HTTPS port and interface
+RE='^((.+?)?,(.+?)?)?$'
+[[ "$T3_PORTS" =~ $RE ]] || usage "Invalid option: '$T3_PORTS'"
+HTTP_PORT=${BASH_REMATCH[2]}
+HTTPS_PORT=${BASH_REMATCH[3]}
 
 HTTP_OPTIONS=
 test -n ${HTTP_PORT} && HTTP_OPTIONS="$HTTP_OPTIONS --publish $HTTP_PORT:80"
 test -n ${HTTPS_PORT} && HTTP_OPTIONS="$HTTP_OPTIONS --publish $HTTPS_PORT:443"
+
+# Split into private key file and certificate file
+RE='^((.+),(.+))?$'
+[[ "$T3_CERTFILES" =~ $RE ]] || usage "Invalid option: '$T3_CERTFILES'"
+KEY_FILE=${BASH_REMATCH[2]}
+CERT_FILE=${BASH_REMATCH[3]}
 
 # Volume names and working directories
 ROOT_MP=
@@ -858,10 +880,10 @@ esac
 case "$CMD" in
 
     run)
-        # Roll back if command fails or is interrupted
-        trap "echo $'\n*** Command failed or interrupted, rolling back ***'; $0 stop -e '$T3_ENGINE' -n '$T3_NAME' --rm; exit 1" ERR SIGINT
+        # Roll back if command terminates prematurely
+        trap "echo $'\n*** Command failed or interrupted, rolling back ***'; $0 stop -e '$T3_ENGINE' -n '$T3_NAME' --rm; exit 1" EXIT
 
-        # Create and run the TYPO3 container
+        # Create the TYPO3 container
         set -e
         echo '*** '"Preparing container '$T3_NAME' ..."' ***'
         run_engine create \
@@ -876,14 +898,23 @@ case "$CMD" in
             $ENV_OPTIONS \
             $@ \
             $T3_IMAGE${T3_TAG:+:$T3_TAG}
+
+        # Copy certificate files, if any
+        if [ -n "$T3_CERTFILES" ]; then
+            run_engine cp "$KEY_FILE" "$T3_NAME":${CERT_BASENAME}.key
+            run_engine cp "$CERT_FILE" "$T3_NAME":${CERT_BASENAME}.crt
+        fi
         echo '*** '"Container '$T3_NAME' created"' ***'
 
+        # Start the container
         run_engine start "$T3_NAME"
         echo '*** '"Container '$T3_NAME' started"' ***'
 
         # Eventually bind-mount container volumes in userspace
         mount_volume "$T3_ROOT" "$ROOT_MP"
         mount_volume "$T3_DB_DATA" "$DB_DATA_MP"
+
+        trap - EXIT
         ;;
 
 
