Test MODE persistence in Travis builds

diff --git a/runtime-files/usr/local/bin/init b/runtime-files/usr/local/bin/init
--- a/runtime-files/usr/local/bin/init
+++ b/runtime-files/usr/local/bin/init
@@ -38,6 +38,8 @@ common_name() {
 # Use the same environment as during build
 . /etc/environment
 
+trap "echo \$'\n*** Fatal error, container not started ***'" EXIT
+
 # Things to do only on startup (but not on subsequent t3 commands)
 if [ $$ -eq 1 ]; then
     # Show version info, trying to get the actual TYPO3 version from composer.lock
@@ -130,6 +132,7 @@ fi
 # Set up developer/XDebug/production mode
 # Use the most recent mode (if any) as default
 MODE=${MODE:-$RECENT_MODE}
+RECENT_MODE=$MODE
 
 case "${MODE,,}" in
 	dev)
@@ -141,6 +144,7 @@ case "${MODE,,}" in
     xdebug)
 		echo "Apache/TYPO3 in developer mode with XDebug support"
 		MODE=dev
+        RECENT_MODE=xdebug
         XDEBUG=y
 		;;
 
@@ -151,9 +155,8 @@ case "${MODE,,}" in
 		;;
 
 	*)
-		echo "Unknown mode: '$MODE'. Defaulting to production mode"
-		MODE=prod
-        XDEBUG=
+		echo "Unknown mode: '$MODE'"
+        exit 1
 		;;
 esac
 
@@ -161,7 +164,7 @@ ln -sf /etc/apache2/conf.d/mode.conf.${MODE} /etc/apache2/conf.d/mode.conf
 ln -sf /etc/php7/mode.${MODE}.template /etc/php7/conf.d/zz_50_mode.ini
 
 sed -e '/^ *export *RECENT_MODE *=/d' -i /etc/environment 
-echo "export RECENT_MODE=$MODE" >>/etc/environment
+echo "export RECENT_MODE=$RECENT_MODE" >>/etc/environment
 
 # php.ini setting overrides
 export \
@@ -211,10 +214,7 @@ if [ -f $COMPOSER_EXCLUDE_FILE ] && [ -n "$(cat $COMPOSER_EXCLUDE_FILE)" ]; then
 fi
 
 if [ $$ -eq 1 ]; then
-    # Notify when this process exits
-    trap "echo \$'\n*** Container stopped ***'" EXIT
-
-    # Start SQLite/MariaDB/PostgreSQL if so requested
+    # Start SQLite/MariaDB/PostgreSQL if so requested,
     echo
 
     # Accept abbreviated database types
