Do not start if Composer Mode cannot be enabled

diff --git a/runtime-files/usr/local/bin/init b/runtime-files/usr/local/bin/init
--- a/runtime-files/usr/local/bin/init
+++ b/runtime-files/usr/local/bin/init
@@ -107,27 +107,24 @@ EOF
     fi
 
     # Deactivate Composer Mode if so requested
-    while true; do
-        if [ -n "$T3_COMPOSER_MODE" ]; then
-            if [ -f $TYPO3_ROOT/composer.json ] && \
-                grep -q -E 'define *\( *'"'TYPO3_COMPOSER_MODE'"' *, *TRUE *\)' $TYPO3_ROOT/vendor/typo3/autoload-include.php; then
-                echo 'TYPO3 extensions to be added/removed by Composer (Composer Mode)'
-                break;
-
-            else
-                echo 'Cannot enable Composer Mode: already disabled in an existing volume'
-            fi
+    if [ -n "$T3_COMPOSER_MODE" ]; then
+        if [ -f $TYPO3_ROOT/composer.json ] && \
+            grep -q -E 'define *\( *'"'TYPO3_COMPOSER_MODE'"' *, *TRUE *\)' $TYPO3_ROOT/vendor/typo3/autoload-include.php; then
+            echo 'TYPO3 extensions have to be added/removed by Composer (Composer Mode)'
+            break;
 
         else
-            sed -E \
-                -e "s/define *\( *'TYPO3_COMPOSER_MODE' *, *TRUE *\) *;/define('TYPO3_COMPOSER_MODE', FALSE);/" \
-                -i $TYPO3_ROOT/vendor/typo3/autoload-include.php
-            rm -rf $TYPO3_ROOT/composer.* $APACHE_HOME/.composer
+            echo 'Cannot enable Composer Mode: it is already disabled in an existing volume'
+            exit 1
         fi
 
-        echo 'TYPO3 extensions to be added/removed by the TYPO3 Extension Manager'
-        break
-    done
+    else
+        sed -E \
+            -e "s/define *\( *'TYPO3_COMPOSER_MODE' *, *TRUE *\) *;/define('TYPO3_COMPOSER_MODE', FALSE);/" \
+            -i $TYPO3_ROOT/vendor/typo3/autoload-include.php
+        rm -rf $TYPO3_ROOT/composer.* $APACHE_HOME/.composer
+        echo 'TYPO3 extensions have to be added/removed by the TYPO3 Extension Manager'
+    fi
 fi
 
 # Set up developer/XDebug/production mode
