Display error line in tests

diff --git a/compose-files/usr/local/bin/composer b/compose-files/usr/local/bin/composer
--- a/compose-files/usr/local/bin/composer
+++ b/compose-files/usr/local/bin/composer
@@ -26,7 +26,7 @@ if [ -n "$SAVED_COMPOSER_EXCLUDE" ]; then
         if [ -n "$D" -a -d "$TYPO3_ROOT/$D" ]; then
             SAVE_DIR=$(mktemp -d)
             rsync -aq "$TYPO3_ROOT/$D/" $SAVE_DIR/
-            echo "Excluded '$D'"
+            echo "Saved '$D'"
             TRAP_CMDS="rm -rf '$TYPO3_ROOT/$D/'"'*'"; rsync -aq $SAVE_DIR/ '$TYPO3_ROOT/$D/' && echo \"Restored '$D'\"; $TRAP_CMDS"
             trap "set +e; $TRAP_CMDS" EXIT
 
@@ -43,6 +43,6 @@ if [ -n "$RUN_COMPOSER" ]; then
         -s /bin/sh -l \
         -c ". /etc/environment; /usr/local/bin/composer.phar --working-dir=\$TYPO3_ROOT $*"
 else
-    echo "Cannot satisfy COMPOSER_EXCLUDE constraints, therefore Composer was not run" >&2
+    echo "Cannot fulfill COMPOSER_EXCLUDE requirements, therefore Composer was not run" >&2
     exit 1
 fi
