Refactor container environment handling

diff --git a/compose-files/usr/local/bin/composer b/compose-files/usr/local/bin/composer
--- a/compose-files/usr/local/bin/composer
+++ b/compose-files/usr/local/bin/composer
@@ -3,27 +3,27 @@
 #
 # Runs Composer as user $APACHE_USER and in working directory $TYPO3_ROOT.
 #
-# Beforehand, all directories listed in $COMPOSER_EXCLUDE_FILE are copied to
+# Beforehand, all directories listed in $COMPOSER_EXCLUDE are copied to
 # temporary directories. Afterwards, these directories are restored.
 #
 
 . /etc/environment
 
 if [ ! -r $TYPO3_ROOT/composer.json ]; then
-    echo "File $TYPO3_ROOT/composer.json not found; Composer Mode apparently not active" 1>&2
-    exit -1
+    echo "File $TYPO3_ROOT/composer.json not found; Composer Mode apparently not active" >&2
+    exit 1
 fi
 
 RUN_COMPOSER=1
 
-if [ -f $COMPOSER_EXCLUDE_FILE ] && [ -n "$(cat $COMPOSER_EXCLUDE_FILE)" ]; then
+if [ -n "$COMPOSER_EXCLUDE" ]; then
     COMPOSER_EXCLUDE_ROOT=$APACHE_HOME/composer-exclude
 
     # Copy directories to exclude, making sure that each one is restored afterwards
     set -e
     TRAP_CMDS=
 
-    while IFS=':' read -ra DIRS; do
+    echo $COMPOSER_EXCLUDE | while IFS=':' read -ra DIRS; do
         for D in "${DIRS[@]}"; do
             if [ -n "$D" -a -d $TYPO3_ROOT/$D ]; then
                 SAVE_DIR=$(mktemp -d)
@@ -37,7 +37,7 @@ if [ -f $COMPOSER_EXCLUDE_FILE ] && [ -n "$(cat $COMPOSER_EXCLUDE_FILE)" ]; then
                 RUN_COMPOSER=
             fi
         done
-    done <<< "$(cat $COMPOSER_EXCLUDE_FILE)"
+    done
 fi
 
 # Run Composer in TYPO3 context
diff --git a/runtime-files/usr/local/bin/init b/runtime-files/usr/local/bin/init
--- a/runtime-files/usr/local/bin/init
+++ b/runtime-files/usr/local/bin/init
@@ -5,6 +5,10 @@
 # and runs what was given as command line arguments
 # =================================================
 #
+# This script is run by 't3 run' and is re-run by 't3' commands
+# which could alter the container environment such as 't3 env'
+# and 't3 composer'.
+#
 # Copyright F. Kasper <fkasper@modus-operandi.at> 2019
 #
 # This program is free software: you can redistribute it and/or modify
@@ -39,7 +43,7 @@ common_name() {
 . /etc/environment
 
 
-# Things to do only on startup (but not on subsequent t3 commands)
+# Initial invocation of this script (i.e. by 't3 run')?
 if [ $$ -eq 1 ]; then
     # Show version info, trying to get the actual TYPO3 version from composer.lock
     RE='^([0-9]+\.){2,}[0-9]+'
@@ -56,6 +60,15 @@ $(php --version)
 
 EOF
 
+    # Get the values of container environment variables
+    # as set by '--env T3_NAME=VALUE'
+    RE='^(T3_('$RE_CONT_ENV'))=(.*)$'
+    while read -r ENV_VAR; do
+        if [[ "$ENV_VAR" =~ $RE ]]; then
+            export ${BASH_REMATCH[2]}=${BASH_REMATCH[3]}
+        fi
+    done <<< "$(printenv)"
+
     # Try to determine the local timezone if none was specified
     [ -z "$TIMEZONE" ] && TIMEZONE="$(curl -s https://ipapi.co/timezone)"
 
@@ -69,15 +82,6 @@ EOF
 
     # Show locale
     echo "Locale: $LANG"
-
-    # Obtain the initial values of alterable environment variables
-    # from the container environment (set by '--env T3_NAME=VALUE')
-    RE='^(T3_('$ALTERABLES'))=(.*)$'
-    while read -r ENV_VAR; do
-        if [[ "$ENV_VAR" =~ $RE ]]; then
-            export ${BASH_REMATCH[2]}=${BASH_REMATCH[3]}
-        fi
-    done <<< "$(printenv)"
 
     # Disable the default SSL configuration in favor of the TYPO3 SSL configuration
     mv /etc/apache2/conf.d/ssl.conf /etc/apache2/conf.d/ssl.conf.disabled
@@ -135,6 +139,18 @@ EOF
         rm -rf $TYPO3_ROOT/composer.* $APACHE_HOME/.composer
         echo 'TYPO3 extensions have to be added/removed by the TYPO3 Extension Manager'
     fi
+
+else
+    # Script invoked by a command after 't3 run' such as 't3 env', 't3 composer'
+
+    # Merge the previous state of the container environment variables
+    # with what may have been specified in the current 't3' command
+    RE='^(SAVED_('$RE_CONT_ENV'))=(.*)$'
+    while read -r ENV_VAR; do
+        if [[ "$ENV_VAR" =~ $RE ]]; then
+            eval "export ${BASH_REMATCH[2]}=\${${BASH_REMATCH[2]}:-\$SAVED_${BASH_REMATCH[2]}}"
+        fi
+    done <<< "$(printenv)"
 fi
 
 
@@ -159,7 +175,7 @@ case "${MODE,,}" in
         ;;
 
     *)
-        echo "Unknown mode: '$MODE'"
+        echo "Unknown mode: '$MODE'" >&2
         exit 1
         ;;
 esac
@@ -199,30 +215,27 @@ fi
 # root created missing paths for volumes also in $APACHE_HOME, therefore:
 chown -R $APACHE_USER: $APACHE_HOME 
 
-# Save/update the list of directories to be excluded from Composer operations
-# only if $COMPOSER_EXCLUDE has been set to any (even an empty) value
-if [ ! -z ${COMPOSER_EXCLUDE+x} ]; then
-    echo "$COMPOSER_EXCLUDE" > $COMPOSER_EXCLUDE_FILE
-fi
+# Show the list of directories to be excluded from Composer operations
+if [ -n "$COMPOSER_EXCLUDE" ]; then
+    echo "Excluded from Composer operations:"
 
-if [ -f $COMPOSER_EXCLUDE_FILE ] && [ -n "$(cat $COMPOSER_EXCLUDE_FILE)" ]; then
-    echo "Excluded from Composer:"
+    echo $COMPOSER_EXCLUDE | \
     while IFS=':' read -ra DIRS; do
         for D in "${DIRS[@]}"; do
             echo "  $D"
         done
-    done <<< "$(cat $COMPOSER_EXCLUDE_FILE)"
+    done
 fi
 
-# Save alterable environment variables for the next invocation of this script
-sed -e '/^ *export +('$ALTERABLES') *=/d' -i /etc/environment
+# Save the container environment state for the next invocation of this script
+sed -e '/^ *export +('$RE_CONT_ENV') *=/d' -i /etc/environment
 
-RE='^('$ALTERABLES')=(.*)$'
+RE='^('$RE_CONT_ENV')=(.*)$'
 while read -r ENV_VAR; do
     if [[ "$ENV_VAR" =~ $RE ]]; then
         VALUE=${BASH_REMATCH[2]}
         VALUE=${VALUE//"'"/"'"\""'"\""'"}  # insert double-quotes around each single quote
-        echo "export ${BASH_REMATCH[1]}='$VALUE'" >>/etc/environment
+        echo "export SAVED_${BASH_REMATCH[1]}='$VALUE'" >>/etc/environment
     fi
 done <<< "$(printenv)"
 
@@ -235,7 +248,7 @@ if [ $$ -eq 1 ]; then
     [[ -n $T3_DB_TYPE && mariadb == ${T3_DB_TYPE,,}* ]] && start_mysql && DB_SUCCESS=1
     [[ -n $T3_DB_TYPE && postgresql == ${T3_DB_TYPE,,}* ]] && start_pg && DB_SUCCESS=1
     [[ -z $T3_DB_TYPE || sqlite == ${T3_DB_TYPE,,}* ]] && start_sqlite && DB_SUCCESS=1
-    [[ -n $DB_SUCCESS ]] || { echo "Unknown database type or startup failure: '$T3_DB_TYPE'"; exit 1; }
+    [[ -n $DB_SUCCESS ]] || { echo "Unknown database type or startup failure: '$T3_DB_TYPE'" >&2; exit 1; }
 fi
 
 # Execute Dockerfile CMD or command line, passing host signals to the exec'd process
